import { jsPDF } from "jspdf"

interface Vulnerability {
  id: string
  name: string
  severity: "low" | "medium" | "high"
  description: string
  category: string
}

interface Recommendation {
  id: string
  vulnerabilityId: string
  title: string
  description: string
  priority: "low" | "medium" | "high"
  implementation: string
}

export function exportToPDF(vulnerabilities: Vulnerability[], recommendations: Recommendation[]) {
  const doc = new jsPDF()

  // Set up colors
  const primaryColor = [59, 130, 246] // Blue
  const textColor = [15, 23, 42] // Dark slate
  const grayColor = [100, 116, 139] // Slate gray

  // Header
  doc.setFontSize(24)
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2])
  doc.text("Mobile App Security Analysis Report", 20, 30)

  // Date and summary
  doc.setFontSize(12)
  doc.setTextColor(grayColor[0], grayColor[1], grayColor[2])
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 45)
  doc.text(`Total Vulnerabilities Found: ${vulnerabilities.length}`, 20, 55)

  // Severity breakdown
  const highCount = vulnerabilities.filter((v) => v.severity === "high").length
  const mediumCount = vulnerabilities.filter((v) => v.severity === "medium").length
  const lowCount = vulnerabilities.filter((v) => v.severity === "low").length

  doc.setFontSize(16)
  doc.setTextColor(textColor[0], textColor[1], textColor[2])
  doc.text("Executive Summary", 20, 75)

  doc.setFontSize(12)
  doc.text(`• High Severity: ${highCount} vulnerabilities`, 25, 90)
  doc.text(`• Medium Severity: ${mediumCount} vulnerabilities`, 25, 100)
  doc.text(`• Low Severity: ${lowCount} vulnerabilities`, 25, 110)

  let yPosition = 130

  // Vulnerabilities section
  doc.setFontSize(16)
  doc.setTextColor(textColor[0], textColor[1], textColor[2])
  doc.text("Detailed Vulnerabilities", 20, yPosition)
  yPosition += 20

  vulnerabilities.forEach((vuln, index) => {
    if (yPosition > 270) {
      doc.addPage()
      yPosition = 30
    }

    doc.setFontSize(14)
    doc.setTextColor(textColor[0], textColor[1], textColor[2])
    doc.text(`${index + 1}. ${vuln.name}`, 20, yPosition)

    doc.setFontSize(10)
    // Set severity color
    if (vuln.severity === "high") {
      doc.setTextColor(239, 68, 68) // Red
    } else if (vuln.severity === "medium") {
      doc.setTextColor(245, 158, 11) // Amber
    } else {
      doc.setTextColor(59, 130, 246) // Blue
    }
    doc.text(`Severity: ${vuln.severity.toUpperCase()}`, 25, yPosition + 10)

    doc.setTextColor(grayColor[0], grayColor[1], grayColor[2])
    doc.text(`Category: ${vuln.category}`, 25, yPosition + 20)

    // Wrap description text
    const splitDescription = doc.splitTextToSize(vuln.description, 160)
    doc.text(splitDescription, 25, yPosition + 30)

    yPosition += 50 + (splitDescription.length - 1) * 5
  })

  // Recommendations section
  if (yPosition > 220) {
    doc.addPage()
    yPosition = 30
  } else {
    yPosition += 20
  }

  doc.setFontSize(16)
  doc.setTextColor(textColor[0], textColor[1], textColor[2])
  doc.text("Security Recommendations", 20, yPosition)
  yPosition += 20

  recommendations.forEach((rec, index) => {
    if (yPosition > 250) {
      doc.addPage()
      yPosition = 30
    }

    const vuln = vulnerabilities.find((v) => v.id === rec.vulnerabilityId)

    doc.setFontSize(12)
    doc.setTextColor(textColor[0], textColor[1], textColor[2])
    doc.text(`${index + 1}. ${rec.title}`, 20, yPosition)

    if (vuln) {
      doc.setFontSize(10)
      doc.setTextColor(grayColor[0], grayColor[1], grayColor[2])
      doc.text(`For: ${vuln.name}`, 25, yPosition + 10)
      yPosition += 10
    }

    doc.setFontSize(10)
    doc.setTextColor(textColor[0], textColor[1], textColor[2])

    // Wrap recommendation text
    const splitRec = doc.splitTextToSize(rec.description, 160)
    doc.text(splitRec, 25, yPosition + 10)

    const splitImpl = doc.splitTextToSize(`Implementation: ${rec.implementation}`, 160)
    doc.text(splitImpl, 25, yPosition + 20 + (splitRec.length - 1) * 5)

    yPosition += 40 + (splitRec.length - 1) * 5 + (splitImpl.length - 1) * 5
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(grayColor[0], grayColor[1], grayColor[2])
    doc.text(`Page ${i} of ${pageCount} | Mobile Security Analyzer`, 20, 285)
    doc.text("Generated by SecureAnalyzer v0", 150, 285)
  }

  // Save the PDF
  doc.save("mobile-security-analysis-report.pdf")
}
